name: Release Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  docker_publish_latest:
    name: Build and Push Docker (latest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and publish Docker image
        uses: Dennis960/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          context: .
          image_tag: latest,${{ github.run_number }}